--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--INSERT INTO supply_institute (institute_code, institute_name) values ('hcf','주택도시기금');
--
--
--HOUSING_CITY_FUND('hcf','주택도시기금'),
--    KB_BANK('bnk006','국민은행'),
--    WR_BANK('bnk020','우리은행'),
--    SH_BANK('bnk021', '신한은행'),
--    CT_BANK('bnk027','한국씨티은행'),
--    HN_BANK('bnk081','하나은행'),
--    NH_BANK('bnk095','농협은행/수협은행'),
--    KE_BANK('bnk005','외환은행'),
--    ETC_BANK('bnk999','기타은행');